// Post-build step: scans dist/ and emits dist/sw.js with a full precache
// manifest. Hand-rolled (no workbox) so the caching behavior is fully
// auditable. Cache-first for precached files -> app works offline after
// the first load. Cache name embeds a content hash so any rebuild with
// changed output invalidates the old cache on activate.
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIST = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist');

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out;
}

const files = walk(DIST).filter((f) => !f.endsWith('sw.js'));
const hash = createHash('sha256');
const urls = files
  .map((f) => {
    hash.update(readFileSync(f));
    let url = '/' + relative(DIST, f).replaceAll('\\', '/');
    // dist/stats/index.html -> /stats/ ; dist/index.html -> /
    if (url.endsWith('/index.html')) url = url.slice(0, -'index.html'.length);
    return url;
  })
  .sort();

const version = hash.digest('hex').slice(0, 12);

const sw = `// generated by scripts/generate-sw.mjs — do not edit
const CACHE = 'brain-${version}';
const ASSETS = ${JSON.stringify(urls, null, 1)};

// Update flow: a new SW installs alongside the old one and WAITS; the
// page promotes it (message below) whenever no game is actively being
// played, then reloads on controllerchange. This gets updates live on
// the first visit after a deploy without ever yanking assets out from
// under a running trial.
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)));
});

self.addEventListener('message', (e) => {
  if (e.data === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) return;
  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(e.request, { ignoreSearch: true });
    if (hit) return hit;
    if (e.request.mode === 'navigate') {
      // clean-URL navigations: /stats -> precached /stats/
      const path = url.pathname.endsWith('/') ? url.pathname : url.pathname + '/';
      const page = (await cache.match(path)) || (await cache.match('/'));
      if (page) return page;
    }
    try {
      const res = await fetch(e.request);
      if (res.ok) cache.put(e.request, res.clone());
      return res;
    } catch {
      return new Response('offline', { status: 503, statusText: 'offline' });
    }
  })());
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);
console.log(`sw.js written: cache brain-${version}, ${urls.length} precached URLs`);
